-- Create brokers table
CREATE TABLE IF NOT EXISTS brokers (
    code TEXT PRIMARY KEY,
    name TEXT,
    category TEXT,
    character TEXT
);

-- Seed data
INSERT OR IGNORE INTO brokers (code, name, category, character) VALUES
('AD', 'OSO Sekuritas Indonesia', 'Local fund', 'Broker lokal. layanan lengkap untuk nasabah ritel dan institusi'),
('AF', 'Harita Kencana Sekuritas', 'Local fund', 'Broker lokal. bagian dari grup Harita'),
('AG', 'Kiwoom Sekuritas Indonesia', 'Retail', 'Anak usaha Kiwoom Securities Korea. fokus pada platform trading online untuk investor ritel'),
('AH', 'Shinhan Sekuritas Indonesia', 'Foreign fund', 'Bagian dari Shinhan Financial Group (Korea). melayani investor institusi dan ritel'),
('AI', 'UOB Kay Hian Sekuritas', 'Foreign fund', 'Broker asal Singapura. menyediakan jasa pialang dan investasi untuk nasabah institusi dan high‑net‑worth'),
('AK', 'UBS Sekuritas Indonesia', 'Foreign fund', 'Cabang UBS (Swiss). fokus pada layanan investment banking dan pialang institusi'),
('AN', 'Wanteg Sekuritas', 'Local fund', 'Broker lokal kecil. layanan pialang dasar'),
('AO', 'ERDIKHA ELIT SEKURITAS', 'Local fund', 'Pialang lokal. melayani perdagangan saham dan penjamin emisi'),
('AP', 'Pacific Sekuritas Indonesia', 'Local fund', 'Broker lokal. menyediakan jasa brokerage dan investment banking'),
('AR', 'Binaartha Sekuritas', 'Local fund', 'Perusahaan riset dan pialang lokal. dikenal dengan analisa pasar'),
('AT', 'Phintraco Sekuritas', 'Local fund', 'Broker lokal. layanan bagi investor ritel serta korporasi'),
('AZ', 'Sucor Sekuritas', 'Local fund', 'Pialang lokal terkemuka; fokus pada riset, manajemen aset, dan investor ritel.  '),
('BB', 'Verdhana Sekuritas Indonesia', 'Local fund', 'Broker lokal. skala menengah'),
('BF', 'Inti Fikasa Sekuritas', 'Local fund', 'Pialang lokal. layanan terbatas'),
('BK', 'J.P. Morgan Sekuritas Indonesia', 'Foreign fund', 'Unit dari J.P. Morgan (AS). melayani transaksi institusi dan investment banking'),
('BQ', 'Korea Investment and Sekuritas Indonesia', 'Foreign fund', 'Anak perusahaan Korea Investment & Securities. mengeluarkan produk derivatif dan melayani investor institusi'),
('BR', 'Trust Sekuritas', 'Local fund', 'Pialang lokal. volume transaksi kecil'),
('BS', 'Equity Sekuritas Indonesia', 'Local fund', 'Broker lokal. penyedia layanan pialang'),
('CC', 'MANDIRI SEKURITAS', 'Retail', 'Broker milik BUMN. salah satu pialang terbesar dengan fokus institusi dan ritel'),
('CD', 'Mega Capital Sekuritas', 'Local fund', 'Pialang lokal. bagian dari CT Corp'),
('CP', 'KB Valbury Sekuritas', 'Foreign fund', 'Joint‑venture antara KB Securities (Korea) dan Valbury. melayani institusi'),
('DD', 'Makindo Sekuritas', 'Local fund', 'Pialang lokal. skala kecil'),
('DH', 'SINARMAS SEKURITAS', 'Local fund', 'Bagian dari Sinarmas Group. broker lokal terkemuka'),
('DP', 'DBS Vickers Sekuritas Indonesia', 'Foreign fund', 'Anak usaha DBS Bank (Singapura). fokus institusi'),
('DR', 'RHB Sekuritas Indonesia', 'Foreign fund', 'Joint‑venture RHB (Malaysia). melayani institusi dan korporasi'),
('DU', 'KAF Sekuritas Indonesia', 'Foreign fund', 'Pialang asal Malaysia. melayani institusi dan ritel'),
('DX', 'Bahana Sekuritas', 'Local fund', 'Pialang BUMN. fokus investment banking dan institusi'),
('EL', 'Evergreen Sekuritas Indonesia', 'Local fund', 'Broker lokal kecil.  '),
('EP', 'MNC Sekuritas', 'Retail', 'Bagian dari MNC Group. platform digital untuk nasabah ritel'),
('ES', 'EKOKAPITAL SEKURITAS', 'Local fund', 'Pialang lokal. aktivitas rendah'),
('FO', 'Forte Global Sekuritas', 'Local fund', 'Broker lokal. dimiliki Indra Boedijono (55%) dan Adi Haryom (45%)'),
('FS', 'Yuanta Sekuritas Indonesia', 'Foreign fund', 'Anak usaha Yuanta Financial Holdings (Taiwan). menawarkan layanan pialang dan investment banking'),
('FZ', 'Waterfront Sekuritas Indonesia', 'Local fund', 'Pialang lokal. status perusahaan lokal menurut APEI'),
('GA', 'BNC Sekuritas Indonesia', 'Local fund', 'Broker lokal skala kecil.  '),
('GI', 'Webull Sekuritas Indonesia', 'Retail', 'Dimiliki oleh Webull Corporation (AS). platform investasi digital untuk ritel'),
('GR', 'PANIN SEKURITAS Tbk.', 'Local fund', 'Bagian dari Panin Group. pialang dan investment banking'),
('GW', 'HSBC Sekuritas Indonesia', 'Foreign fund', 'Cabang dari HSBC (UK). fokus pada klien institusi'),
('HD', 'KGI Sekuritas Indonesia', 'Foreign fund', 'Anak usaha KGI Securities (Taiwan). melayani institusi dan ritel'),
('HP', 'Henan Putihrai Sekuritas', 'Local fund', 'Broker lokal dengan status ‘Lokal’ pada APEI.  '),
('IC', 'Integrity Capital Sekuritas', 'Local fund', 'Pialang lokal.  '),
('ID', 'Anugerah Sekuritas Indonesia', 'Local fund', 'Pialang lokal. berfokus pada nasabah ritel'),
('IF', 'SAMUEL SEKURITAS INDONESIA', 'Local fund', 'Perusahaan sekuritas lokal. terkenal dengan riset dan investment banking'),
('IH', 'Indo Harvest Sekuritas', 'Local fund', 'Broker lokal kecil.  '),
('II', 'Danatama Makmur Sekuritas', 'Local fund', 'Pialang lokal. melayani emisi dan brokerage'),
('IN', 'INVESTINDO NUSANTARA SEKURITA', 'Local fund', 'Broker lokal.  '),
('IP', 'Yugen Bertumbuh Sekuritas', 'Local fund', 'Pialang lokal. banyak melayani ritel'),
('IT', 'INTI TELADAN SEKURITAS', 'Local fund', 'Broker lokal.  '),
('IU', 'Indo Capital Sekuritas', 'Local fund', 'Pialang lokal.  '),
('KI', 'Ciptadana Sekuritas Asia', 'Local fund', 'Pialang lokal papan atas; melayani institusi, ritel, dan layanan wealth.  '),
('KK', 'Phillip Sekuritas Indonesia', 'Retail', 'Joint‑venture dengan PhillipCapital Singapura. dikenal sebagai broker asing retail'),
('KZ', 'CLSA Sekuritas Indonesia', 'Foreign fund', 'Cabang CLSA (Hong Kong). fokus pada riset dan transaksi institusi'),
('LG', 'Trimegah Sekuritas Indonesia Tbk.', 'Local fund', 'Perusahaan sekuritas lokal besar; menyediakan layanan pialang, underwriting, dan riset.  '),
('LS', 'Reliance Sekuritas Indonesia Tbk.', 'Local fund', 'Pialang lokal. bagian dari grup Reliance Indonesia'),
('MG', 'Semesta Indovest Sekuritas', 'Local fund', 'Pialang lokal.  '),
('MI', 'Victoria Sekuritas Indonesia', 'Local fund', 'Broker lokal.  '),
('MU', 'Minna Padi Investama Sekuritas', 'Local fund', 'Pialang lokal. memiliki layanan ritel'),
('NI', 'BNI Sekuritas', 'Retail', 'Anak usaha Bank Negara Indonesia. broker BUMN dengan layanan ritel dan institusi'),
('OD', 'BRI Danareksa Sekuritas', 'Local fund', 'Pialang BUMN (BRI & Danareksa). fokus pada investment banking dan ritel'),
('OK', 'NET SEKURITAS', 'Local fund', 'Terafiliasi dengan Grup Salim; 59,5% saham dimiliki Hindarto Budiono.  '),
('PC', 'FAC Sekuritas Indonesia', 'Local fund', 'Pialang lokal.  '),
('PD', 'Indo Premier Sekuritas', 'Retail', 'Broker lokal independen dengan platform IPOT. populer di kalangan ritel'),
('PF', 'Danasakti Sekuritas Indonesia', 'Local fund', 'Broker lokal.  '),
('PG', 'Panca Global Sekuritas', 'Local fund', 'Pialang lokal.  '),
('PI', 'Magenta Kapital Sekuritas Indonesia', 'Local fund', 'Broker lokal. mendapatkan kembali status anggota bursa pada 2024'),
('PO', 'Pilarmas Investindo Sekuritas', 'Local fund', 'Pialang lokal. menyediakan platform online dan riset'),
('PP', 'Aldiracita Sekuritas Indonesia', 'Local fund', 'Perusahaan sekuritas lokal.  '),
('PS', 'PARAMITRA ALFA SEKURITAS', 'Local fund', 'Broker lokal.  '),
('QA', 'Tuntun Sekuritas Indonesia', 'Local fund', 'Pialang lokal.  '),
('RB', 'Ina Sekuritas Indonesia', 'Local fund', 'Perusahaan pialang lokal.  '),
('RF', 'Buana Capital Sekuritas', 'Local fund', 'Broker lokal. menyediakan layanan pialang dan investment banking'),
('RG', 'Profindo Sekuritas Indonesia', 'Local fund', 'Pialang lokal.  '),
('RO', 'Pluang Maju Sekuritas', 'Retail', 'Pialang lokal yang rebranding dari Nilai Inti Sekuritas. berfokus pada platform digital Pluang'),
('RS', 'Yulie Sekuritas Indonesia Tbk.', 'Local fund', 'Broker lokal.  '),
('RX', 'Macquarie Sekuritas Indonesia', 'Foreign fund', 'Unit Macquarie Group (Australia). melayani klien institusi'),
('SA', 'Elit Sukses Sekuritas', 'Local fund', 'Pialang lokal.  '),
('SF', 'Surya Fajar Sekuritas', 'Local fund', 'Pialang lokal. bagian dari Surya Fajar group'),
('SH', 'Artha Sekuritas Indonesia', 'Local fund', 'Broker lokal.  '),
('SQ', 'BCA Sekuritas', 'Retail', 'Anak usaha Bank Central Asia. kuat di penjamin emisi dan riset'),
('SS', 'Supra Sekuritas Indonesia', 'Local fund', 'Pialang lokal.  '),
('TF', 'Laba Sekuritas Indonesia', 'Local fund', 'Broker lokal.  '),
('TP', 'OCBC Sekuritas Indonesia', 'Foreign fund', 'Anak usaha OCBC Bank (Singapura). dipindah ke unit Global Markets untuk fokus klien institusi'),
('TS', 'Dwidana Sakti Sekuritas', 'Local fund', 'Pialang lokal.  '),
('XA', 'NH Korindo Sekuritas Indonesia', 'Foreign fund', 'Joint venture NH Investment & Securities (Korea) dan Korindo. melayani ritel dan institusi'),
('XC', 'Ajaib Sekuritas Asia', 'Retail', 'Perusahaan sekuritas digital. fokus pada investor ritel muda dengan aplikasi Ajaib'),
('XL', 'Stockbit Sekuritas Digital', 'Retail', 'Pialang digital. bagian dari platform Stockbit'),
('YB', 'Yakin Bertumbuh Sekuritas', 'Local fund', 'Broker lokal.  '),
('YJ', 'Lotus Andalan Sekuritas', 'Local fund', 'Pialang lokal.  '),
('YO', 'Amantara Sekuritas Indonesia', 'Local fund', 'Broker lokal.  '),
('YP', 'Mirae Asset Sekuritas Indonesia', 'Retail', 'Cabang Mirae Asset (Korea). populer di kalangan investor ritel'),
('YU', 'CGS International Sekuritas Indonesia', 'Foreign fund', 'Joint venture antara China Galaxy Securities & CIMB (Malaysia). broker asing'),
('ZP', 'Maybank Sekuritas Indonesia', 'Foreign fund', 'Broker patungan Maybank. bagian dari grup Malaysia'),
('ZR', 'Bumiputera Sekuritas', 'Local fund', '');
