name = "bpjs-uid-3380"
account_id = "5a6c75ee2f334a79233aeebffda06de5"
compatibility_date = "2025-10-29"
main = "index.js"

[[kv_namespaces]]
binding = "REKO_KV"
id = "89337288d9564a449eb99664973aa3cb"

[durable_objects]
bindings = [
	{ name = "OTP_DO_NAMESPACE", class_name = "OtpDO" }
]

[[migrations]]
tag = "v1"
new_classes = [ "OtpDO" ]

[vars]
WORKER_BASE_UUID = "https://bpjs-uid-3380.mkemalw.workers.dev"

# Notes:
# - This worker expects `REKO_KV` (KV namespace) to contain user public keys under key `user:<phone>`
#   stored as a JSON string with an exported JWK (recommended).
# - Do not commit secrets (use `wrangler secret put` for any runtime secrets).